
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: (devel)
  creationTimestamp: null
  name: switchportconfigurations.metal3.io
spec:
  group: metal3.io
  names:
    kind: SwitchPortConfiguration
    listKind: SwitchPortConfigurationList
    plural: switchportconfigurations
    singular: switchportconfiguration
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        description: SwitchPortConfiguration is the Schema for the switchportconfigurations
          API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: SwitchPortConfigurationSpec defines the desired state of
              SwitchPortConfiguration
            properties:
              acls:
                items:
                  description: ACL ...
                  properties:
                    action:
                      enum:
                      - allow
                      - deny
                      type: string
                    des:
                      type: string
                    desPortRange:
                      pattern: ([0-9]{1,})|([0-9]{1,}-[0-9]{1,})(,([0-9]{1,})|([0-9]{1,}-[0-9]{1,}))*
                      type: string
                    protocol:
                      enum:
                      - TCP
                      - UDP
                      - ICMP
                      - ALL
                      type: string
                    src:
                      type: string
                    srcPortRange:
                      pattern: ([0-9]{1,})|([0-9]{1,}-[0-9]{1,})(,([0-9]{1,})|([0-9]{1,}-[0-9]{1,}))*
                      type: string
                    type:
                      enum:
                      - ipv4
                      - ipv6
                      type: string
                  type: object
                maxItems: 10
                type: array
              linkAggregationType:
                enum:
                - lag
                - mlag
                type: string
              untaggedVLAN:
                type: string
              vlans:
                items:
                  type: string
                maxItems: 3
                type: array
            type: object
          status:
            description: SwitchPortConfigurationStatus defines the observed state
              of SwitchPortConfiguration
            type: object
        type: object
    served: true
    storage: true
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
